### ISSUE TITLE
타임라인용 게시판의 목록에서만 원본글 게시판정보 노출

### ISSUE THREAD

**Issue by wookho** [izuzero/xe-module-timeline#15]
저도 시용해보니 어떤게시판에 작성되서 올라온 글인지 나오면 좋겠는데요.
스킨 수정방법을 스킨개발자가 아니라도 수정해 볼수 있는 안내가 있으면 좋겠습니다.

스케치북5 스킨을 예제로 설명을 해주신 좋을것 같습니다.

**Comment by izuzero** [comment]
예제를 올리게 되면 싫어도 관련 질문이 들어오게 돼 있고, 일일이 스킨을 봐드려야 하기 때문에 올리지 않습니다. 베타1 버전 올릴 때 관련 질문은 받지 않는다고 적어놓기도 했고요.
꼭 필요하시다면 딱 한 번만 수정해드릴 순 있습니다.

**Comment by wookho** [comment]
그렇군요. 설명을 듣고 스스로 해보려고 해서 드린 의견인데요. 알겠습니다.
파일을 드리도록 할게요.

**Comment by wookho** [comment]
@izuzero 여기는 이미지만 첨부가 되어 압축파일을 메일로 보내드렸습니다.
감사합니다.

**Comment by wookho** [comment]
감사합니다. 주신파일로 적용하니 각각의 게시판정보가 잘 표시됩니다.
