### ISSUE TITLE
타임라인 게시판으로 익명게시판의 댓글 작성시 익명이 풀리는 현상

### ISSUE THREAD

**Issue by Canto** [izuzero/xe-module-timeline#17]
일반 게시물은 게시판모듈의 익명 설정을 후킹 해와서 제대로 작성이 됩니다만
댓글 작성시 익명이 풀리는 현상이 보입니다.

**Comment by izuzero** [comment]
#11

**Comment by Canto** [comment]
아 참고로 beta3에서 확인된 현상이에요!

**Comment by izuzero** [comment]
후킹 과정 이리 저리 바꾸다가 빼먹었나 봅니다;;

**Comment by izuzero** [comment]
자료실에는 1.0.0-beta3 버전 배포를 건너뛰고 1.0.0-beta4 버전을 배포하겠습니다.

**Comment by Canto** [comment]
정상적으로 동작하는 것을 확인했습니다.. 늦은 시간까지 감사합니다 ^^
