### ISSUE TITLE
원게시판 명 불러오는 것에 대한 문의

### ISSUE THREAD

**Issue by wookho** [izuzero/xe-module-timeline#18]
스케치북5스킨 원글의 게시판명 불러오는거 수정해주셔서 잘 사용하고 있습니다. 
그런데 한가지 풀리지 않는 의문이 하나 있어서요. 

바로 화제의글애드온을 통해 상단공지에 게시글이 노출이 되는데요. 어떤 타임라인게시판에는 화제의글에도 원게시판이 잘 표시되는데 특정 타임라인에는 화제의글에만 해당부분에 빈텍스트로 출력이 됩니다.
개발자도구를 통해 보면 <스트롱></스트롱> 이런식으로 게시판 이름이 비어져 있습니다.

http://pomelove.com/xe/localboard

요 게시판이 그 중 하나인데요. 혹시 살펴봐주실 수 있나요 ?

**Comment by wookho** [comment]
고민을 해보니 다른곳과 차이를 알것 같은데 해결책은 모르겠네요 ㅋ
일단 다른곳과 달리 이 곳은 지역게시판만 모아 놓은 곳이다 보니 화제의글로 뜬 글들이 속한 게시판이 이 타임라인에서 불러온 글들에서는 없어서 표시를 못해주는 것 같네요.

화제의글애드온에서 불러온 글들의 게시판이 => 타임라엔에서 불러온 게시판에 포함되어 있어야 표시가 가능한 것 같습니다.

**Comment by wookho** [comment]
closed

**Comment by izuzero** [comment]
타임라인 게시판으로 지정된 모듈만 표시됩니다.
