### ISSUE TITLE
게시글 필터 추가 옵션 건의

### ISSUE THREAD

**Issue by KrissHeo** [izuzero/xe-module-timeline#19]
추천 10 이상으로 추천글게시판을 운영하는 경우를 가정할 때,
추천 10, 비추천 50인 글도 추천글 대상이 됩니다.
그러면 추천글에 적합하지 못한 글임에도 추천글 게시판에 업로드되겠지요.

이를 막기 위해, 추천, 비추천을 동시에 고려하는 필터링 옵션이 추가되면 어떨까 싶습니다.

예를 들어,
필터링 옵션에 추천/비추천의 값을 넣는 것입니다.
추천/비추천 = 1 이면 추천과 비추천의 수가 같다는 것이고
추천/비추천 = 1.5이면 추천이 비추천에 비해 1.5배 높다는 뜻이니
각각 비율로 따지면 50%, 75%가 되겠죠.

물론 이 옵션은 단독으로 사용하면 곤란하고,
추천, 비추천 필터링을 사용할 때에만 작동해야 합니다.
(모든 게시물은 기본적으로 추천 0, 비추천 0이므로
비추천으로 나누는 연산을 수행하면 0으로 나누는 연산이 되니까요)

이 옵션이 추가되면
기존에 존재하던 옵션인 '추천 n이상'과 혼용하여
'추천은 n개를 넘고, 추천/비추천의 값이 m 이상(초과)일 때'
로 추천글보기 게시판을 더 효율적으로 운영할 수 있을 거라고 생각합니다.

**Comment by izuzero** [comment]
비율로는 구현하기 힘들어서 추천수와 비추천수의 차이값을 필터 옵션에 추가했습니다.

**Comment by KrissHeo** [comment]
빠른 의견수렴 감사합니다!
