### ISSUE TITLE
타임라인 게시판에서 회원정보의 작성글보기 스크랩보기 오류 입니다.

### ISSUE THREAD

**Issue by wookho** [izuzero/xe-module-timeline#23]
제가 확인한 증상은 이렇네요. 타임라인으로 쓰는 게시판에 머무를때 회원정보기를 통해 작성글 보기를 하면 타임라인에 불어와진 게시물 모두가 내가 작성한 글로 나오네요. 스크랩은 이상한 목록이 나열되구요. 제목없는....

일반 게시판에서 회원정보기에서 내가작성한글 스크랩은 정상적입니다.

**Comment by izuzero** [comment]
확인했습니다.
