### ISSUE TITLE
특정게시판에서는 특정 기준의 게시물만 가져오는 기능

### ISSUE THREAD

**Issue by socialskyo** [izuzero/xe-module-timeline#26]
지금 통합 게시판 모듈은 필터링 기능이 있찌만 선택된 게시판에 일괄 적용 됩니다.

그런데 특정 게시판은 특정 필터링만 적용 되는 기능이 추가 되면 해당 필터링 기능이 완벽해지지 않나 싶습니다. 

예를 들어 특정 게시판이 뉴스 게시판이라면, 뉴스 중에서 특정 키워드/추천수/댓글수등에 걸러진 뉴스만 통합되어 보여진다면...모든 뉴스(쓸데없는) 가 게시판에 통합 되지 않고도 통합 게시판이 더욱 유용해질 것 같습니다.

**Comment by izuzero** [comment]
이 이슈는 논의되지 않습니다.
게시판마다 게시글을 가져오는 조건이 다르면 DB 쿼리 사용 시 소모되는 서버 자원이 많아지기 때문에 속도상의 우려가 있습니다.

**Comment by socialskyo** [comment]
그렇군요 !! 잘 알겠습니다.
