### ISSUE TITLE
XE 타임라인사용시 페이지 넘어가는 글링크에러

### ISSUE THREAD

**Issue by saramjh** [izuzero/xe-module-timeline#27]
타임라인으로 사용되는 게시판에서 2페이지 이상의 페이지의 글을 열람하여
본문으로 이동할시에 해당 페이지의 순서로 이동되어 해당글에서 표시되는 글은 목록이 없거나
전혀 다른 페이지를 표시하게됩니다.

ex) 타임라인게시판에서 2번페이지의 자유게시판추출의 1번글을 클릭
자유게시판으로 이동하여보면 자유게시판의 추출글은 정상표시되나
글과 함께 보는 목록은 추출글이 1페이지에있었으나 2페이지를 표시.

이런 문제가 있습니다.

**Comment by izuzero** [comment]
타임라인 모듈의 문제는 아닌데... '원래 게시판으로 이동' 옵션을 사용하면 페이지 번호를 초기화하도록 개선하겠습니다.
