### ISSUE TITLE
최신글 모아보기~~~

### ISSUE THREAD

**Issue by ppleo** [izuzero/xe-module-timeline#28]
옵션에 있는 기간 설정이 아니라

최근 24시간이든 일정시간을 정하면 그 시간 내의 글을 모아 볼수 있으면 좋을 듯합니다. ^^

**Comment by izuzero** [comment]
기준 날짜를 안 정하면 현재 시간으로부터 시간 범위 내의 글만 불러오는 스펙이 이미 정의되어 있습니다.

**Comment by ppleo** [comment]
오호 그렇군요..그 런의미로 되여있군요. 확인 해보겠습니다. 감사합니다.
