### ISSUE TITLE
기간조건이 필요합니다.

### ISSUE THREAD

**Issue by wookho** [izuzero/xe-module-timeline#3]
현재 기간이 없어서 사이트 게시물에대한 추천 조회 등의 조건에 따른 베스트게시판은 운영이 가능하나
많이 이용하는 일간 주간 월간 베스트를 운영하기 위해서는 기간조건이 필요할 것 같습니다.

**Comment by wookho** [comment]
위젯이나 화제의글애드온에서 사용하는 설정값 시간범위라는 항목을 타임라인의 개별모듈 (주간베스트,월간베스트 등) 에도 적용하여 게시판에 용도에 따라 시간을 입력할수 있으면 좋겠습니다. 

현재 게시물을 일정추천수,일정조회수 조건으로 선택하여 타임라인에서 보여주는데 이 조건 외 단순히 현재 시점으로 부터 입력된 시간 이전의 게시물만 가져오는 것이 하나 더 있었으면 합니다.

Ex) 1. 모든조건 사용하지 않고  시간범위에 168시간을 넣으면 주간에 작성된 게시물이 모두 대상이 됩니다.
여기서 타임라인의 게시판설정의 목록 출력 정렬을 추천순으로 설정해주면 주간베스트가 됩니다.

Ex) 2. 추천 10개 시간범위 168시간을 설정하고 게시판 목록은 추천 또는 최신순으로 하면 추천을 기준으로한 주간 화제의글들이 됩니다.

이렇게 입력받은 시간안의 게시물을 대상으로만 출력이 가능할지 궁금하네요. 시간마다 체크해서 범위에서 벗어난 게시물은 대상에서 빼고 새로운 대상을 넣어줘야 하니까요. 위젯의 시간범위의 개념입니다.

**Comment by izuzero** [comment]
기준 날짜 및 시간이 필요하고, 그로부터 얼마만큼의 시간 범위에 있는 글을 뽑아올지, 지정한 시간 범위가 지났을 경우 기준 날짜 및 시간을 자동으로 갱신할 건지 정하는 설정이 필요합니다.
단시간에 해결될 일은 아닌 것 같습니다.

**Comment by wookho** [comment]
단순하게 위젯의 시간범위 조건을 적용은 어려울까요? 캐시적용이 병행되어야 db사용 부담이 덜하겠지만요.

168시간을 적용하면

해당게시판 목록에는 지금부터 168시간전 까지의 게시물만 나타나는거죠.

주간 월간 단위의 게시판을 만들려다보니 이런게 필요하네요.

**Comment by wookho** [comment]
기준이 되는 시간은 방문자가 목록에 접근하는 시간이 되고 설정값이 168시간이라면 게시핀을 클릭하는 순간부터 168시간 이전 까지의 게시물이 목록에 뿌려지게 됩니다. 여기에 캐시가 적용된다면 적용된캐시 동안은 같은 목록을 계속 보여주구요.

**Comment by izuzero** [comment]
d0f88ce 커밋을 적용하고 잘 되는지 확인해주세요.

**Comment by wookho** [comment]
@izuzero 기준날짜와 날짜범위의 개념을 이해하지 못하겠습니다.

**Comment by wookho** [comment]
![set](https://cloud.githubusercontent.com/assets/6590236/5769907/77ddebf8-9d65-11e4-80c5-33b992b110ec.png)

위와 같이 설정했는데 기간과 상관없이 모든 게시물이 출력되네요.

http://pomelove.com/xe/index.php?mid=mbest

**Comment by wookho** [comment]
날짜 범위를 매일 수동으로 바꿔줘야 30일간 베스트를 사용할 수 있는건가요 ? 아니면 날짜범위가 자동으로 갱신이 되나요 ?

**Comment by wookho** [comment]
![set1](https://cloud.githubusercontent.com/assets/6590236/5770048/d3df7ea6-9d67-11e4-9c92-730724c10e70.png)

이렇게 해야 오늘 30일간 게시물 대상으로 매일 자동으로 추출이 되는건가요 ???

**Comment by wookho** [comment]
질문드리겠습니다. 오늘 2015년 1월 16일에는 2014년 12월 16일 까지의 게시물을 대상으로 해야 하구요.

하루가 지난 내일 2015년 1월 17일에는 2014년 12월 17일 까지의 게시물을 대상으로 매일 최근 30일간 의 게시물을 대상으로 하려면 어떻게 설정을 해야 하는건가요 ?

**Comment by izuzero** [comment]
설정 옆에 물음표 버튼 클릭하면 설명을 보실 수 있습니다만...

기준 날짜는 절대값으로 입력해야 하는 값이고, 날짜 범위는 상대값으로 입력해야 하는 값입니다.
기준 날짜 2015년 1월 1일, 날짜 범위 1일로 지정하면 2015년 1월 1일 하루동안만의 게시글만 불러오게 되는 것이고, 기준 날짜 없이 날짜 범위  1일만 지정하면 지금으로부터 24시간 이내의 글만 불러오게 됩니다.
기준 날짜를 2015년 1월 1일, 날짜 범위를 1일로 지정했는데 지금 시간이 2015년 1월 2일 1시이고, 기준 날짜 갱신 기능을 사용한다면 기준 날짜를 자동으로 2015년 1월 2일로 바꿔 저장합니다.

**Comment by wookho** [comment]
@izuzero 조금 이해하기 힘드네요. 현재 날짜범위도 절대값을 넣게 되어 있는것 처럼 저는 보이는데요...

**Comment by wookho** [comment]
![set2](https://cloud.githubusercontent.com/assets/6590236/5771199/9e69632c-9d7b-11e4-8215-c2f27d293ce3.png)

@izuzero 제가 이해력이 좀 딸렸나 봅니다. 그럼 이렇게 하면 최근 30일 기준이 자동으로 된다는 말씀이시죠 ?

**Comment by izuzero** [comment]
네 맞습니다.

**Comment by wookho** [comment]
@izuzero 아이고 감사합니다. 저는 두개 모두 절대날짜를 넣어야 하는줄 알고 엄청 고민했습니다. 말씀하신대로 잘 동작합니다. 감사합니다.

위젯 없이도 모듈로 통합게시판,베스트게시판,월간베스트,주간베스트,일간베스트 이슈글 모두 만들수 있네요. 이건 공모전 1등 받아야 합니다 ㅋ

**Comment by izuzero** [comment]
기능 사용을 이해하기 어렵다고 하셨으니 저는 기능 이름과 설명을 조금 다듬도록 하겠습니다. :)

**Comment by wookho** [comment]
아참,,  공모전 요거 때문에 바쁘신거 같은데요. 나중에 짬 나시면 
https://github.com/izuzero/xe-module-ajaxboard-plugins/issues/11 요것도 좀 살펴봐주시면... 굽신굽신~~~
