### ISSUE TITLE
모듈이 작동하지 않습니다.

### ISSUE THREAD

**Issue by minsujang0** [izuzero/xe-module-timeline#30]
코어버전 1.7.3.2
게시판 모듈 1.7.1.1
인데 혹시 최소 지원 버전 이하라서 안되는 것일까요?

**Comment by izuzero** [comment]
무엇이 안 된다는 것인지 모르겠습니다.
증상을 자세히 적어주세요.

**Comment by minsujang0** [comment]
아하.... 죄송합니다 게시판 생성 후 모듈 설정에서 타임라인으로 쓸 게시판 지정, 보여줄 게시판 지정하고 시간 설정에서 기준일은 건드리지 않고 아래의 기한만 7일로 설정해서 그 외의 옵션은 놔둔채로 설정했는데 게시판에 아무 것도 나타나지 않습니다.

**Comment by izuzero** [comment]
7일 이내에 작성된 게시글이 있는지 확인하세요.

**Comment by minsujang0** [comment]
실제로 사용중인 사이트라서 7일 이내에 작성된 게시글은 존재합니다.
