### ISSUE TITLE
게시글 작성 및 댓글 작성 시 해당 게시판 설정으로 동기화

### ISSUE THREAD

**Issue by izuzero** [izuzero/xe-module-timeline#4]
게시판 권한이 타임라인 게시판으로 귀속되는 문제가 있다.
타임라인 게시판에서 게시글과 댓글을 달면 해당 게시판 설정으로 동기화해줄 필요가 있다.

**Comment by wookho** [comment]
이게 타 모듈에서 제어하는 권한까지 동기화 되나요? 예를 들면 아이템샵이나 레벨별권한모듈 등에서 제어하는것이요.

**Comment by izuzero** [comment]
@wookho
커밋 적용하고도 안 되시나요

**Comment by wookho** [comment]
@izuzero 네. 마켓에서 판매하는 레벨별권한모듈 사용중인 게시판 타임라인에 포함했는데 비회원도 열람이 가능하더라구요.

**Comment by wookho** [comment]
@izuzero 관련해서는 새로운 이슈로 등록해 드렸습니다. 게시판 기본권한 설정 문제가 아니라서요.
