### ISSUE TITLE
타모듈에의해 권한이 설정된 것의 무시

### ISSUE THREAD

**Issue by wookho** [izuzero/xe-module-timeline#5]
마켓에서 판매하는 레벨권한모듈을 사용하고 있습니다.
특정 게시판들은 열람권한이 레벨로 설정되어 있는데 타임라인으로 편입시키면 권한이 무시되고 열람이 가능해져 통합게시판 운영에 어려움이 있습니다.

**Comment by izuzero** [comment]
f9522ec 커밋을 적용하고 잘 되는지 확인해주세요.

**Comment by wookho** [comment]
@izuzero 감사합니다. 아주 잘 됩니다!
